### ISSUE TITLE
loadmore模块的api似乎已经失效，可能是忘记更新了 一下是我截取的Log输出

### ISSUE THREAD

**Issue by WeiYongqiang55** [liaohuqiu/android-cube-app#31]
900 29727-29993/in.srain.cube.demo D/cube-request: RequestData: [http://www.android-cube-app-server.liaohuqiu.net/api/image-list.php?token=&start=0&num=5, G: {token=, start=0, num=5}, P: null, F: null]
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err: java.net.ConnectException: failed to connect to skykiwi-demo.liaohuqiu.net/106.186.29.127 (port 80): connect failed: ETIMEDOUT (Connection timed out)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:114)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at java.net.Socket.connect(Socket.java:843)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:131)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:101)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at in.srain.cube.request.sender.BaseRequestSender.getResponse(BaseRequestSender.java:53)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at in.srain.cube.request.DefaultRequestProxy.doSyncRequest(DefaultRequestProxy.java:43)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at in.srain.cube.request.DefaultRequestProxy.requestSync(DefaultRequestProxy.java:58)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at in.srain.cube.request.SimpleRequest.doRequestSync(SimpleRequest.java:30)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at in.srain.cube.request.RequestBase.requestSync(RequestBase.java:22)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at in.srain.cube.demo.datamodel.DemoUploadModel$2.run(DemoUploadModel.java:41)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at java.lang.Thread.run(Thread.java:841)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err: Caused by: libcore.io.ErrnoException: connect failed: ETIMEDOUT (Connection timed out)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at libcore.io.Posix.connect(Native Method)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:85)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:127)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:112)
12-07 09:58:22.867 29727-29742/in.srain.cube.demo W/System.err: 	... 20 more

**Comment by chain911** [comment]
对的
